server {
    listen 5678;
    listen [::]:5678;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    # SPA : toute route inconnue retombe sur index.html (react-router)
    location / {
        try_files $uri /index.html;
    }
}
